package com.alphaStS;

public enum DebuffType {
    VULNERABLE,
    WEAK,
    FRAIL,
    NO_MORE_CARD_DRAW,
    LOSE_STRENGTH,
    LOSE_DEXTERITY,
    LOSE_STRENGTH_EOT,
    LOSE_DEXTERITY_EOT,
    ENTANGLED,
    HEX,
    LOSE_FOCUS,
    LOSE_FOCUS_PER_TURN,
    CONSTRICTED,
    DRAW_REDUCTION,
}
