package com.alphaStS;

public enum GameActionType {
    BEGIN_BATTLE,
    PLAY_CARD,
    SELECT_ENEMY,
    SELECT_CARD_DISCARD,
    SELECT_CARD_HAND,
    SELECT_CARD_EXHAUST,
    SELECT_CARD_DECK,
    SELECT_CARD_1_OUT_OF_3,
    END_TURN,
    USE_POTION,
    BEGIN_PRE_BATTLE,
    SELECT_SCENARIO,
    BEGIN_TURN,
    END_SELECT_CARD_HAND,
    END_SELECT_CARD_1_OUT_OF_3,
    AFTER_RANDOMIZATION,
}
