package com.alphaStS;

public enum RandomGenCtx {
    CardDraw,
    EnemyChooseMove,
    CardGeneration,
    RandomEnemySwordBoomerang,
    RandomEnemyJuggernaut,
    RandomEnemyGeneral,
    RandomEnemyLightningOrb,
    RandomEnemyRipAndTear,
    RandomCardHand,
    RandomCardHandMummifiedHand,
    RandomCardHandWarpedTongs,
    ShieldGremlin,
    GremlinLeader,
    BronzeOrb,
    Chaos,
    ShieldAndSpire,
    Snecko,
    RandomCardGen,
    SkillPotion,
    PowerPotion,
    Misc,
    CommonNumberVR,
    BeginningOfGameRandomization,
    Other,
}
