package com.alphaStS;

public enum RandomGenCtx {
    CardDraw,
    EnemyChooseMove,
    RandomEnemySwordBoomerang,
    RandomEnemyJuggernaut,
    RandomEnemyGeneral,
    RandomEnemyLightningOrb,
    RandomEnemyRipAndTear,
    RandomCardHand,
    RandomCardHandMummifiedHand,
    RandomCardHandWarpedTongs,
    ShieldGremlin,
    GremlinLeader,
    BronzeOrb,
    Chaos,
    ShieldAndSpear,
    Snecko,
    EntropicBrew,
    RandomCardGen,
    SelectCard1OutOf3,
    RandomEnemyHealth,
    Misc,
    CommonNumberVR,
    BeginningOfGameRandomization,
    Other,
}
